name: verify_gui
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2025.2.25
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.16
  - pip=24.2
  - python=3.8.20
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - altgraph==0.17.4
      - coloredlogs==15.0.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - filelock==3.16.1
      - flatbuffers==25.2.10
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - humanfriendly==10.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - maraboupy==2.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - netron==8.2.8
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - onnx==1.16.0
      - onnxruntime==1.17.3
      - opencv-python-headless==4.11.0.86
      - packaging==25.0
      - pandas==2.0.3
      - pillow==10.4.0
      - protobuf==5.29.4
      - pydot==3.0.4
      - pyinstaller==6.13.0
      - pyinstaller-hooks-contrib==2025.3
      - pyparsing==3.1.4
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.16
      - pyqt5-sip==12.15.0
      - pyqtgraph==0.13.3
      - pyqtwebengine==5.15.7
      - pyqtwebengine-qt5==5.15.16
      - python-dateutil==2.9.0.post0
      - python-graphviz==0.20.3
      - pytz==2025.2
      - seaborn==0.13.2
      - six==1.17.0
      - sympy==1.13.3
      - torch==2.4.1
      - torchaudio==2.4.1
      - torchvision==0.19.1
      - triton==3.0.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - wurlitzer==3.1.1
      - zipp==3.20.2
